version: '3'

services:
  db:
    image: dannyma/psql-docker:1.0.0
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'

  sqlpad:
    image: sqlpad/sqlpad:5.5
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      SQLPAD_AUTH_DISABLED: 'true'
      SQLPAD_AUTH_DISABLED_DEFAULT_ROLE: 'admin'
      SQLPAD_APP_LOG_LEVEL: debug
      SQLPAD_WEB_LOG_LEVEL: warn
      SQLPAD_CONNECTIONS__psql__name: psql
      SQLPAD_CONNECTIONS__psql__driver: postgres
      SQLPAD_CONNECTIONS__psql__host: db
      SQLPAD_CONNECTIONS__psql__username: postgres
      SQLPAD_CONNECTIONS__psql__multiStatementTransactionEnabled: 'true'
      SQLPAD_CONNECTIONS__psql__idleTimeoutSeconds: 86400

  jupyter:
    image: jupyter/scipy-notebook:6d42503c684f
    depends_on:
      - db
    ports:
      - "8888:8888"
    volumes:
      - ./Python:/home/jovyan
    command: "start-notebook.sh \
        --NotebookApp.allow_password_change=True \
        --NotebookApp.token='DataWithDanny'"